[workspace]
resolver = "2"
members = [
    "crates/svpflow-capi",
    "crates/svpflow-core",
    "crates/svpflow-host",
    "crates/svpflow-wasm",
    "crates/svpflow1",
    "crates/svpflow2",
]

[workspace.package]
version = "0.1.0"

[profile.release]
codegen-units = 1
lto = true
panic = "abort"
strip = "symbols"
